### ISSUE TITLE
Digest Input Size

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Intersection-Report#2]
Hello, is it possible to add Digest Input Size in this script?

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id in commit c6de100dd17b402d6dccca41b0fc5c4e39da6701 I have added several new digest input size related value generators.  You can downloaded an updated release with this here: https://github.com/Nuix/Intersection-Report/releases/tag/v2.5.0
