### ISSUE TITLE
Being able to search content only in Provided Terms

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Intersection-Report#4]
We are trying to use the intersection report with the search module report. However in our search module we only search on content and intersection report doesn't give you the ability to choose how to search the terms on each record. Can we apply this?

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id the terms you provide on the "Provided Terms" tab can include field names which I believe would accomplish what you are looking for.

![image](https://user-images.githubusercontent.com/11775738/99104715-346fdb00-2596-11eb-8d5f-98575ebb9efd.png)
![image](https://user-images.githubusercontent.com/11775738/99104759-45b8e780-2596-11eb-8650-6901e79c4d04.png)

**Comment by ccastillo-id** [comment]
Yup this works! thanks
